package com.example.demo.entity;
// Generated 2019-5-23 10:08:53 by Hibernate Tools 5.2.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HotSaleOrderData generated by hbm2java
 */
@Entity
@Table(name="hot_sale_order_data"
)
public class HotSaleOrderData  implements java.io.Serializable {


     private String productId;
     private String productNm;
     private Long orderAmount;

    public HotSaleOrderData() {
    }

	
    public HotSaleOrderData(String productId) {
        this.productId = productId;
    }
    public HotSaleOrderData(String productId, String productNm, Long orderAmount) {
       this.productId = productId;
       this.productNm = productNm;
       this.orderAmount = orderAmount;
    }
   
     @Id 

    
    @Column(name="product_id", unique=true, nullable=false, length=16)
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }

    
    @Column(name="product_nm", length=32)
    public String getProductNm() {
        return this.productNm;
    }
    
    public void setProductNm(String productNm) {
        this.productNm = productNm;
    }

    
    @Column(name="order_amount", precision=12, scale=0)
    public Long getOrderAmount() {
        return this.orderAmount;
    }
    
    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }




}


