package com.example.demo.entity;
// Generated 2019-5-23 10:08:53 by Hibernate Tools 5.2.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LeadingCompOrderData generated by hbm2java
 */
@Entity
@Table(name="leading_comp_order_data"
)
public class LeadingCompOrderData  implements java.io.Serializable {


     private String compId;
     private String compNm;
     private Long orderAmount;

    public LeadingCompOrderData() {
    }

	
    public LeadingCompOrderData(String compId) {
        this.compId = compId;
    }
    public LeadingCompOrderData(String compId, String compNm, Long orderAmount) {
       this.compId = compId;
       this.compNm = compNm;
       this.orderAmount = orderAmount;
    }
   
     @Id 

    
    @Column(name="comp_id", unique=true, nullable=false, length=16)
    public String getCompId() {
        return this.compId;
    }
    
    public void setCompId(String compId) {
        this.compId = compId;
    }

    
    @Column(name="comp_nm", length=32)
    public String getCompNm() {
        return this.compNm;
    }
    
    public void setCompNm(String compNm) {
        this.compNm = compNm;
    }

    
    @Column(name="order_amount", precision=12, scale=0)
    public Long getOrderAmount() {
        return this.orderAmount;
    }
    
    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }




}


