package com.ymslx.nkbigdata.entity;
// Generated 2019-5-23 10:08:53 by Hibernate Tools 5.2.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HotSalePlaceOrderData generated by hbm2java
 */
@Entity
@Table(name="hot_sale_place_order_data"
)
public class HotSalePlaceOrderData  implements java.io.Serializable {


	private String placeId;
    private String placeNm;
    private Long orderAmount;

   public HotSalePlaceOrderData() {
   }

	
   public HotSalePlaceOrderData(String placeId) {
       this.placeId = placeId;
   }
   public HotSalePlaceOrderData(String placeId, String placeNm, Long orderAmount) {
      this.placeId = placeId;
      this.placeNm = placeNm;
      this.orderAmount = orderAmount;
   }
  
    @Id 

   
   @Column(name="place_id", unique=true, nullable=false, length=16)
   public String getPlaceId() {
       return this.placeId;
   }
   
   public void setPlaceId(String placeId) {
       this.placeId = placeId;
   }

   
   @Column(name="place_nm", length=32)
   public String getPlaceNm() {
       return this.placeNm;
   }
   
   public void setPlaceNm(String placeNm) {
       this.placeNm = placeNm;
   }

   
   @Column(name="order_amount", precision=12, scale=0)
   public Long getOrderAmount() {
       return this.orderAmount;
   }
   
   public void setOrderAmount(Long orderAmount) {
       this.orderAmount = orderAmount;
   }




}


