package com.ymslx.nkbigdata.entity;
// Generated 2019-5-23 10:08:53 by Hibernate Tools 5.2.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HotSalePlaceOrderDataId generated by hbm2java
 */
@Embeddable
public class HotSalePlaceOrderDataId  implements java.io.Serializable {


     private String placeId;
     private String placeNm;
     private Long orderAmount;

    public HotSalePlaceOrderDataId() {
    }

	
    public HotSalePlaceOrderDataId(String placeId, String placeNm) {
        this.placeId = placeId;
        this.placeNm = placeNm;
    }
    public HotSalePlaceOrderDataId(String placeId, String placeNm, Long orderAmount) {
       this.placeId = placeId;
       this.placeNm = placeNm;
       this.orderAmount = orderAmount;
    }
   


    @Column(name="place_id", nullable=false, length=24)
    public String getPlaceId() {
        return this.placeId;
    }
    
    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }


    @Column(name="place_nm", nullable=false, length=24)
    public String getPlaceNm() {
        return this.placeNm;
    }
    
    public void setPlaceNm(String placeNm) {
        this.placeNm = placeNm;
    }


    @Column(name="order_amount", precision=12, scale=0)
    public Long getOrderAmount() {
        return this.orderAmount;
    }
    
    public void setOrderAmount(Long orderAmount) {
        this.orderAmount = orderAmount;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HotSalePlaceOrderDataId) ) return false;
		 HotSalePlaceOrderDataId castOther = ( HotSalePlaceOrderDataId ) other; 
         
		 return ( (this.getPlaceId()==castOther.getPlaceId()) || ( this.getPlaceId()!=null && castOther.getPlaceId()!=null && this.getPlaceId().equals(castOther.getPlaceId()) ) )
 && ( (this.getPlaceNm()==castOther.getPlaceNm()) || ( this.getPlaceNm()!=null && castOther.getPlaceNm()!=null && this.getPlaceNm().equals(castOther.getPlaceNm()) ) )
 && ( (this.getOrderAmount()==castOther.getOrderAmount()) || ( this.getOrderAmount()!=null && castOther.getOrderAmount()!=null && this.getOrderAmount().equals(castOther.getOrderAmount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPlaceId() == null ? 0 : this.getPlaceId().hashCode() );
         result = 37 * result + ( getPlaceNm() == null ? 0 : this.getPlaceNm().hashCode() );
         result = 37 * result + ( getOrderAmount() == null ? 0 : this.getOrderAmount().hashCode() );
         return result;
   }   


}


