package com.ymslx.nkbigdata.entity;
// Generated 2019-5-23 10:08:53 by Hibernate Tools 5.2.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LeadingCompProductData generated by hbm2java
 */
@Entity
@Table(name="leading_comp_product_data"
)
public class LeadingCompProductData  implements java.io.Serializable {


     private String compId;
     private String compNm;
     private Long monthProduction;

    public LeadingCompProductData() {
    }

	
    public LeadingCompProductData(String compId) {
        this.compId = compId;
    }
    public LeadingCompProductData(String compId, String compNm, Long monthProduction) {
       this.compId = compId;
       this.compNm = compNm;
       this.monthProduction = monthProduction;
    }
   
     @Id 

    
    @Column(name="comp_id", unique=true, nullable=false, length=16)
    public String getCompId() {
        return this.compId;
    }
    
    public void setCompId(String compId) {
        this.compId = compId;
    }

    
    @Column(name="comp_nm", length=32)
    public String getCompNm() {
        return this.compNm;
    }
    
    public void setCompNm(String compNm) {
        this.compNm = compNm;
    }

    
    @Column(name="month_production", precision=12, scale=0)
    public Long getMonthProduction() {
        return this.monthProduction;
    }
    
    public void setMonthProduction(Long monthProduction) {
        this.monthProduction = monthProduction;
    }




}


